### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by Gsonovb** [echogarden-project/whisper-onnx-models#1]
Hi, 

Can you provide a usage example? thanks

**Comment by rotemdan** [comment]
The model files were exported using a [tool I wrote](https://github.com/echogarden-project/whisper-onnx-exporter), which is using a [modified Whisper core model file](https://github.com/echogarden-project/whisper-onnx-exporter/blob/main/model.py). Other than this core model, I've removed everything.

I didn't write any code to use the exported models in Python. In order do do that you'll need to modify the original OpenAI code to use it. The [`whisper-openvino`](https://github.com/zhuzilin/whisper-openvino) repository has an modified original Whisper Python API that was adapted to use ONNX models. Actually I took their modified model file as a starting point, so there is close similarity between the exported models, and it's possible to refit these models to the modified Python API on that repository (though it's now out-of-date with the main OpenAI repository), but that's not something I'm interested in doing.

It was primarily made for a JavaScript port, which reimplements a large part of the higher-level Whisper functionality in pure TypeScript/JavaScript (however since the models are ONNX, you can use them from any platform, though it would most likely take a lot of work).

In this source file, the Echogarden system uses these models via the `onnxruntime-node` library:

https://github.com/echogarden-project/echogarden/blob/main/src/recognition/WhisperSTT.ts

All the extra processing is done in this file, including extraction of audio features, conversion of tokens, extraction and alignment of timestamps from cross-attention weights, and many other pre- and post-processing steps.

**Comment by Gsonovb** [comment]
Thank you for your reply. I’m just getting started and still need to learn.
